AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function with cfn-response.
Resources:
  primer:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs16.x
      Role: arn:aws:iam::302019044897:role/service-role/myfirsttest-role-tldm2gm4
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = async (event) => {
              // TODO implement
              const response = {
                  statusCode: 200,
                  body: JSON.stringify(' Cloud formation template to  deploy a lambda function!'),
              };
              return response;
          };
      Description: Invoke a function during stack creation.
      TracingConfig:
        Mode: Active